
#include <iostream>
#include <cstdlib>
#include <time.h>
#include <signal.h>
#include <unistd.h>
#include <cstdarg>
#include <string.h>

#include "framebuffer.h"

bool KeepGoing = true;

void static CtrlHandler(int SigNum)
{
	static int numTimesAskedToExit = 0;
	std::cout << std::endl << "Asked to quit, please wait" << std::endl;
	if( numTimesAskedToExit > 2 )
	{
		std::cout << "Asked to quit to many times, forcing exit in bad way" << std::endl;
		exit(1);
	}
	KeepGoing = false;
}

int main(int argc, char *argv[])
{
// Say hello to the world!
    std::cout << "Hello world, a skeleton app generated by appbuild.\n";

// Display the constants defined by app build. \n";
    std::cout << "Application Version " << APP_VERSION << '\n';
    std::cout << "Build date and time " << APP_BUILD_DATE_TIME << '\n';
    std::cout << "Build date " << APP_BUILD_DATE << '\n';
    std::cout << "Build time " << APP_BUILD_TIME << '\n';

    FBIO::FrameBuffer* FB = FBIO::FrameBuffer::Open(true);
	if( !FB )
    {
		return EXIT_FAILURE;
    }

	signal (SIGINT,CtrlHandler);

	srand(time(NULL));

	FB->ClearScreen(100,100,100);

	FBIO::PixelFont TheFont(3);
	TheFont.SetPenColour(0,0,0);

    FB->DrawRectangle(9*8*5,0,19*8*5,13*5,150,150,150,true);
    TheFont.SetPixelSize(5);
    TheFont.Printf(FB,0,0,"Pixel Font %d",rand());

//    FBIO::FreeTypeFont FTFont(FB,"/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",60);
    FBIO::FreeTypeFont FTFont(FB,"./Z003-MediumItalic.otf",90);
    FTFont.SetPenColour(0,0,0);
    FTFont.Printf(FB,10,150,"True Type Font %d",rand());

    FTFont.Print(FB,10,300,"iAlBjXvIoIoiPiTiZilQlFl l l");

    FBIO::FreeTypeFont FTFont2(FB,"./NimbusMonoPS-BoldItalic.otf",60);
    FTFont2.SetPenColour(0,0,0);
    FTFont2.Printf(FB,10,500,"True Type Font %d",rand());

	delete FB;

// And quit";
    return EXIT_SUCCESS;
}
