
#include <iostream>
#include <cstdlib>
#include <time.h>
#include <unistd.h>
#include <cstdarg>
#include <string.h>

#include "framebuffer.h"

int main(int argc, char *argv[])
{
// Say hello to the world!
    std::cout << "Hello world, a skeleton app generated by appbuild.\n";

// Display the constants defined by app build. \n";
    std::cout << "Application Version " << APP_VERSION << '\n';
    std::cout << "Build date and time " << APP_BUILD_DATE_TIME << '\n';
    std::cout << "Build date " << APP_BUILD_DATE << '\n';
    std::cout << "Build time " << APP_BUILD_TIME << '\n';

    FBIO::FrameBuffer* FB = FBIO::FrameBuffer::Open(true);
	if( !FB )
    {
		return EXIT_FAILURE;
    }

	srand(time(NULL));

    const uint8_t BG_R = 255;
    const uint8_t BG_G = 0;
    const uint8_t BG_B = 0;


    FBIO::FreeTypeFont FTFont("./Blenda Script.otf",60,true);
    FTFont.SetBackgroundColour(BG_R,BG_G,BG_B);
    FTFont.SetPenColour(0,255,255);

    FBIO::FreeTypeFont FTFont2("./MachineScript.ttf",45,true);
    FTFont2.SetBackgroundColour(BG_R,BG_G,BG_B);
    FTFont2.SetPenColour(0,255,0);

    while( FB->GetKeepGoing() )
    {
	    FB->ClearScreen(BG_R,BG_G,BG_B);

        FTFont.SetPenColour(0,0,0);
        FTFont.Printf(FB,0,80,"Blenda Script 0123456789 :)");

        FTFont.SetPenColour(0,255,255);
        FTFont.Print(FB,0,180,"Spacing Test iAlBjXvIoiP X l");

        FTFont2.Print(FB,10,300,"Test Number 0123456789");
        FTFont2.Printf(FB,10,400,"Random Number %d",rand());

        FB->Present();
        sleep(1);
    }

	delete FB;

// And quit";
    return EXIT_SUCCESS;
}
